sudo: required
language: java
install: true
script: "./gradlew compileDocker"
services:
- docker
notifications:
  slack:
    secure: mC9UOTeLt7PDbUABFApsQKmAMB9E4WUUGlPAsov2L61G1c/A1vFbqZn6ZXLER/QEBL2orF6517l7J5/FbBLkI2BCuMrP6h/A339swxE3chK3CEz/9uEY54l8mbD7lYZQN6lsboiXZnpE5KYQ/vZsD9oTa8qJkA0D7dfPdg6rSMQyocXy8QDIEcwk+0S2a/PweDKIXWzXhyCTmsvkX7FxFe9+hted0JVIFObsAxXJT7tVQLVuVRADOyKxIDOeYQ6/mAnnGhA3W0tVgCltaUPuapP0V0FxcJcbNEGxZ6javTIM3HCky5beBdTHApTtzFHKDWN+f3sOJrQW9oZThAdb192al+9ndbFreR36btsa8XTvHRDWrExAwqjvRktFuwiWpXmkg/WIjpSCTokEGho+0FxzKJIutAYFLIYqhF1bHLt5L+RlCNO9V9FxQyy7jotKdj46J0OlmTLY45J5nM64ZnjZfqQMwh+vQcNnFtIzGG6CIqxS9MnDHSx6Lq4/kfz4UbY2nK9VkFa+OahGR6Q342vXSrNVgwgQ8HA5UTaDfbau9bTRLnPZv8No5Ruhutl/bW9JwuqPRWi7ipETOPzOGHcwOLc3ojtfb6yXxL0z/8PhuqEvjlsJVqqTuHZnr3fkB8F0SQt+WzkL61sPYeWaT9LbM4M3z3hOOcKfkq+P1VQ=
